backend:
  name: github
  repo: dinzinhosa/site-luana
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "paginas"
    label: "Páginas do Site"
    files:
      - label: "Conteúdo Principal"
        name: "conteudo"
        file: "src/conteudo.json"
        fields:
          - { label: "Nome da Médica", name: "heroNome", widget: "string" }
          - { label: "Especialidade", name: "heroEspecialidade", widget: "string" }
          - { label: "CRM", name: "heroCrm", widget: "string" }
          - { label: "Foto Principal (Início)", name: "imagemHero", widget: "image", required: false }
          - { label: "Frase de Destaque", name: "heroDestaque", widget: "string" }
          - { label: "Título da Consulta", name: "heroTituloConsulta", widget: "string" }
          - { label: "Descrição da Consulta", name: "heroDescricao", widget: "markdown", required: false }
          - { label: "Título da Seção Sobre", name: "sobreTitulo", widget: "string" }
          - { label: "Foto do Consultório (Sobre)", name: "imagemSobre", widget: "image", required: false }
          - { label: "Texto da Seção Sobre", name: "sobreTexto", widget: "markdown", required: false }
          - label: "Título da Seção de Consultas"
            name: "servicosTitulo"
            widget: "string"
            required: false
          - label: "Lista de Especialidades"
            name: "servicos"
            widget: "list"
            fields:
              - { label: "Nome do Transtorno", name: "titulo", widget: "string", required: false }
              - { label: "Descrição", name: "descricao", widget: "markdown", required: false }
          - { label: "Endereço", name: "contatoEndereco", widget: "markdown", required: false }
          - { label: "Telefone", name: "contatoTelefone", widget: "string", required: false }
          - { label: "Link do WhatsApp", name: "contatoLinkZap", widget: "string" }
          - { label: "Título da Seção de Contato", name: "contatoTitulo", widget: "string", required: false }
          - { label: "Texto da Seção de Contato", name: "contatoSubtitulo", widget: "string", required: false }